#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-R.cache
Version  : 0.17.0
Release  : 33
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/R.cache_0.17.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/R.cache_0.17.0.tar.gz
Summary  : Fast and Light-Weight Caching (Memoization) of Objects and
Group    : Development/Tools
License  : LGPL-2.1+
Requires: R-R.methodsS3
Requires: R-R.oo
Requires: R-R.utils
Requires: R-digest
BuildRequires : R-R.methodsS3
BuildRequires : R-R.oo
BuildRequires : R-R.utils
BuildRequires : R-digest
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory structure was created by the R package 'R.cache'
available on CRAN [https://cran.r-project.org/package=R.cache].
It holds cache files containing results memoized by various
R packages that utilize the R.cache package.  It is safe to
delete all or part of these files at any time.  By definition,
if memoized results are missing, they are recalculated by the
R package who needs them/created them in the first place.

%prep
%setup -q -n R.cache
pushd ..
cp -a R.cache buildavx2
popd
pushd ..
cp -a R.cache buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746462591

%install
export SOURCE_DATE_EPOCH=1746462591
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/R.cache/DESCRIPTION
/usr/lib64/R/library/R.cache/INDEX
/usr/lib64/R/library/R.cache/Meta/Rd.rds
/usr/lib64/R/library/R.cache/Meta/features.rds
/usr/lib64/R/library/R.cache/Meta/hsearch.rds
/usr/lib64/R/library/R.cache/Meta/links.rds
/usr/lib64/R/library/R.cache/Meta/nsInfo.rds
/usr/lib64/R/library/R.cache/Meta/package.rds
/usr/lib64/R/library/R.cache/NAMESPACE
/usr/lib64/R/library/R.cache/NEWS.md
/usr/lib64/R/library/R.cache/R/R.cache
/usr/lib64/R/library/R.cache/R/R.cache.rdb
/usr/lib64/R/library/R.cache/R/R.cache.rdx
/usr/lib64/R/library/R.cache/WORDLIST
/usr/lib64/R/library/R.cache/_Rcache/CACHEDIR.TAG
/usr/lib64/R/library/R.cache/_Rcache/README.txt
/usr/lib64/R/library/R.cache/help/AnIndex
/usr/lib64/R/library/R.cache/help/R.cache.rdb
/usr/lib64/R/library/R.cache/help/R.cache.rdx
/usr/lib64/R/library/R.cache/help/aliases.rds
/usr/lib64/R/library/R.cache/help/paths.rds
/usr/lib64/R/library/R.cache/html/00Index.html
/usr/lib64/R/library/R.cache/html/R.css
/usr/lib64/R/library/R.cache/tests/DEPRECATED.R
/usr/lib64/R/library/R.cache/tests/Object.getChecksum.R
/usr/lib64/R/library/R.cache/tests/StaticMethodsAndNamespaces.R
/usr/lib64/R/library/R.cache/tests/addMemoization.R
/usr/lib64/R/library/R.cache/tests/assertDigest.R
/usr/lib64/R/library/R.cache/tests/clearCache.R
/usr/lib64/R/library/R.cache/tests/evalWithMemoization.R
/usr/lib64/R/library/R.cache/tests/findOSCachePath.R
/usr/lib64/R/library/R.cache/tests/getCachePath.R
/usr/lib64/R/library/R.cache/tests/getCacheRootPath.R
/usr/lib64/R/library/R.cache/tests/loadCache.R
/usr/lib64/R/library/R.cache/tests/memoizedCall.R
/usr/lib64/R/library/R.cache/tests/readCacheHeader.R
/usr/lib64/R/library/R.cache/tests/setCachePath.R
/usr/lib64/R/library/R.cache/tests/setCacheRootPath.R
/usr/lib64/R/library/R.cache/tests/textPrompt.R
